[package]
name = "tdecrypt_helper"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.14"
bm25 = "2.3.2"
