[package]
name = "tdector"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rfd = "0.17"
scirs2-text = "0.1.3"
ndarray = "0.17.2"
rhai = "1.24"
